-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 08:32:56 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `id` INT NOT NULL,
  `client_fname` VARCHAR(45) NOT NULL,
  `client_lname` VARCHAR(45) NOT NULL,
  `client_initial` VARCHAR(45) NOT NULL,
  `client_address` VARCHAR(45) NOT NULL,
  `client_contact` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`financial_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`financial_report` (
  `id` INT NOT NULL,
  `fr_amount` VARCHAR(45) NOT NULL,
  `fr_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `id` INT NOT NULL,
  `emp_fname` VARCHAR(45) NOT NULL,
  `emp_lname` VARCHAR(45) NOT NULL,
  `emp_initial` VARCHAR(2) NOT NULL,
  `emp_address` VARCHAR(255) NOT NULL,
  `emp_dob` DATETIME NOT NULL,
  `client_id` INT NOT NULL,
  `financial_report_id` INT NOT NULL,
  PRIMARY KEY (`id`, `client_id`, `financial_report_id`),
  INDEX `fk_employee_client1_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_employee_financial_report1_idx` (`financial_report_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_financial_report1`
    FOREIGN KEY (`financial_report_id`)
    REFERENCES `mydb`.`financial_report` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`commodities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`commodities` (
  `id` INT NOT NULL,
  `com_type` VARCHAR(45) NOT NULL,
  `com_validity` VARCHAR(45) NOT NULL,
  `com_worth` VARCHAR(45) NOT NULL,
  `com_quantity` VARCHAR(45) NOT NULL,
  `com_brand` VARCHAR(45) NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`, `employee_id`),
  INDEX `fk_commodities_employee_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_commodities_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`delivery` (
  `id` INT NOT NULL,
  `del_cour` VARCHAR(45) NOT NULL,
  `del_data_receive` VARCHAR(45) NOT NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`, `client_id`),
  INDEX `fk_delivery_client1_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_delivery_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contract` (
  `id` INT NOT NULL,
  `con_signed` VARCHAR(45) NOT NULL,
  `con_date` DATETIME NOT NULL,
  `con_expiration` DATETIME NOT NULL,
  `client_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  `employee_client_id` INT NOT NULL,
  PRIMARY KEY (`id`, `client_id`, `employee_id`, `employee_client_id`),
  INDEX `fk_contract_client1_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_contract_employee1_idx` (`employee_id` ASC, `employee_client_id` ASC) VISIBLE,
  CONSTRAINT `fk_contract_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contract_employee1`
    FOREIGN KEY (`employee_id` , `employee_client_id`)
    REFERENCES `mydb`.`employee` (`id` , `client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`salary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`salary` (
  `id` INT NOT NULL,
  `sal_amount` VARCHAR(45) NOT NULL,
  `sal_received` VARCHAR(45) NOT NULL,
  `employee_id` INT NOT NULL,
  `employee_client_id` INT NOT NULL,
  PRIMARY KEY (`id`, `employee_id`, `employee_client_id`),
  INDEX `fk_salary_employee1_idx` (`employee_id` ASC, `employee_client_id` ASC) VISIBLE,
  CONSTRAINT `fk_salary_employee1`
    FOREIGN KEY (`employee_id` , `employee_client_id`)
    REFERENCES `mydb`.`employee` (`id` , `client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`training`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`training` (
  `id` INT NOT NULL,
  `trai_location` VARCHAR(45) NOT NULL,
  `trai_num_employ` VARCHAR(45) NOT NULL,
  `employee_id` INT NOT NULL,
  `employee_client_id` INT NOT NULL,
  `employee_financial_report_id` INT NOT NULL,
  PRIMARY KEY (`id`, `employee_id`, `employee_client_id`, `employee_financial_report_id`),
  INDEX `fk_training_employee1_idx` (`employee_id` ASC, `employee_client_id` ASC, `employee_financial_report_id` ASC) VISIBLE,
  CONSTRAINT `fk_training_employee1`
    FOREIGN KEY (`employee_id` , `employee_client_id` , `employee_financial_report_id`)
    REFERENCES `mydb`.`employee` (`id` , `client_id` , `financial_report_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client_has_commodities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client_has_commodities` (
  `client_id` INT NOT NULL,
  `commodities_id` INT NOT NULL,
  `commodities_employee_id` INT NOT NULL,
  PRIMARY KEY (`client_id`, `commodities_id`, `commodities_employee_id`),
  INDEX `fk_client_has_commodities_commodities1_idx` (`commodities_id` ASC, `commodities_employee_id` ASC) VISIBLE,
  INDEX `fk_client_has_commodities_client1_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_client_has_commodities_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_has_commodities_commodities1`
    FOREIGN KEY (`commodities_id` , `commodities_employee_id`)
    REFERENCES `mydb`.`commodities` (`id` , `employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
